MESSAGES = {
    "ko": {
        "title": "📊 기업 재무 분석 도구",
        "subtitle": "고급 재무 진단 시스템 - 포괄적인 기술적 및 기본적 구조 매핑",
        "market_select": "시장 선택:",
        "market_us": "🇺🇸 미국 주식 (Yahoo Finance)",
        "search_method": "검색 방법 선택:",
        "by_ticker": "티커/종목코드로 검색",
        "by_name": "회사명으로 검색",
        "enter_ticker": "미국 주식 티커 입력 (예: AAPL):",
        "enter_ticker_kr": "한국 주식 종목코드 6자리 입력 (예: 005380):",
        "enter_name": "회사명 입력 (예: Apple, Tesla, Oracle):",
        "select_company": "정확한 회사 선택:",
        "search_error": "⚠️ 검색 한계량 도달 혹은 네트워크 지연이 발생했습니다. 티커 검색 방식을 이용하시면 막힘없이 사용 가능합니다.",
        "search_error_kr": "⚠️ 한국 주식 종목 검색 중 오류가 발생했습니다. 종목 코드(6자리 숫자)로 직접 입력해 주세요.",
        "fetch_error_kr": "⚠️ 한국 주식 데이터를 가져오지 못했습니다. DART API Key가 올바른지, 종목 코드가 맞는지 확인해 주세요.",
        "partial_data_warning": "⚠️ 일부 기본 재무 데이터가 부족하여 분석이 제한될 수 있습니다. 기술적 데이터와 보유 지표를 기반으로 표시합니다.",
        "partial_data_info": "현재는 가격 및 기술적 지표 중심으로 결과가 제공됩니다. DART API 네트워크 제한이 풀리면 추가 재무 지표가 자동으로 표시됩니다.",
        "tab_report": "📝 종합의견 (Report)",
        "tab_overview": "📌 개요 (Overview)",
        "tab_ichimoku": "📐 일목균형표 (Ichimoku)",
        "tab_bs": "🏢 재무상태표 (Balance Sheet)",
        "tab_ratios": "📊 주요 비율 (Ratios)",
        "tab_valuation": "📉 가치평가 (Valuation)",
        "tab_tech": "📊 보조지표 (Technical)",
        "tab_tech_title": "📊 기술적 지표 요약",
        "tech_insufficient_data": "기술적 지표 계산에 필요한 충분한 데이터가 없습니다. 최근 가격 추세와 거래량을 확인해 주세요.",
        "rsi_overbought": "RSI가 70 이상이면 과매수 구간입니다. 단기 조정 가능성을 유의하세요.",
        "rsi_oversold": "RSI가 30 이하이면 과매도 구간입니다. 반등 신호로 해석할 수 있습니다.",
        "rsi_neutral": "RSI는 중립 권역입니다. 추세 확인과 추가 지표를 함께 보세요.",
        "macd_bullish": "MACD가 Signal 위에 있어 상승 모멘텀이 강화되고 있습니다.",
        "macd_bearish": "MACD가 Signal 아래에 있어 하락 압력이 우세합니다.",
        "macd_neutral": "MACD가 Signal과 유사한 위치에 있어 방향성 판단이 제한적입니다.",
        "obv_up": "OBV가 증가하면 매수 거래량이 누적되고 있음을 의미합니다.",
        "obv_down": "OBV가 감소하면 매도 거래량 우위가 지속되고 있음을 의미합니다.",
        "obv_flat": "OBV가 횡보하면 거래량 동력이 약해 추세 확인이 필요합니다.",
        "tech_summary_title": "현재 기술적 지표 기반 종목 상황",
        "tech_summary_intro": "아래 지표는 선택한 종목의 최근 주가 흐름을 기반으로 한 현재 기술적 상태입니다.",
        "tab_news": "📰 뉴스 (News)",
        "report_title": "📝 실시간 재무·주가 종합 진단 보고서",
        "target_comp": "대상 기업",
        "section1": "🔍 1. 최근 주가 수준 및 기술적·밸류에이션 평가",
        "section2": "📊 2. 핵심 재무 상태 스코어링",
        "section3": "💡 3. 최종 투자 전략 가이드라인 (CVP 융합)",
        "curr_price": "현재 주가",
        "range_52": "52주 주가 변동 범위",
        "at_location": "현재 변동폭의",
        "location_end": "지점 위치",
        "avg_50": "단기 균형 가격 (50일 평균)",
        "multiple_analysis": "멀티플 분석: 현재 PER 지표는",
        "ichimoku_analysis": "##### 📐 일목균형표(Ichimoku) 추세 모멘텀 분석",
        "growth_score": "성장성 점수 (매출액 변동)",
        "profit_score": "수익성 점수 (당기순이익 변동)",
        "stability_score": "부채 안정성 (부채비율)",
        "liquidity_score": "유동성 리스크 (유동비율)",
        "total_score_text": "종합 재무 건전성 평점",
        "excellent": "✅ 우수",
        "stagnant": "❌ 정체",
        "safe": "✅ 안전",
        "high_debt": "🚨 부채 과다",
        "caution_cash": "🚨 현금 주의",
        "report_good": "💎 **재무 종합 의견:** 펀더멘탈이 대단히 우량한 기업입니다. 주가 조정 발생 시 분할 매수 접근 전략이 유효합니다.",
        "report_neutral": "⚠️ **재무 종합 의견:** 성장성 혹은 안정성 중 특정 지표의 둔화가 관찰됩니다. 마진율 변동 추이를 추적 관찰해야 합니다.",
        "report_bad": "🚨 **재무 종합 의견:** 전반적인 재무 지표 역성장 및 유동성 리스크가 우려됩니다. 보수적인 투자 관점이 필요합니다.",
        "guideline_1": "1. **비용 구조 개방:** 본 기업의 현재 분기 추정 손익분기점(BEP) 매출액은 **{currency}{bep_sales:,.0f}**입니다. 현재 매출이 손익분기점을 안전하게 상회하고 있으므로 고정비 레버리지 효과에 따른 수익성 확대 국면입니다.",
        "guideline_2": "2. **운전 자본 효율성:** 현금전환주기(CCC)가 **{ccc:.1f}일**로 측정되어 자금 회수 속도가 원활한 편입니다. 공급망 리스크에 따른 재고자산 누적 여부를 체크하시기 바랍니다.",
        "guideline_3": "3. **최종 결론:** 본 재무분석 시스템의 추정치인 주당 가치 스케일링을 기준으로 볼 때, 현재 주가는 재무 기초체력 대비 합리적인 흐름을 보이고 있으나, 단기 변동성을 감안하여 실시간 뉴스 탭에 올라오는 글로벌 이슈들을 병행 모니터링하시기 바랍니다.",
        "disclaimer": "⚠️ **Investment Disclaimer** ※ 본 자료 및 검토의견은 재무제표와 관련 자료를 기초로 작성된 참고용 정보이며, 투자 권유 또는 투자 수익을 보장하는 내용이 아닙니다. 투자 결정에 대한 최종 책임은 사용자에게 있으며, 이 정보로 인한 손해에 대해 본 시스템은 책임을 지지 않습니다.",
        "status_high": "🔴 **52주 최고점 근접 구역 (과열 경계):** 현재 주가는 52주 가격 밴드 최상단에 위치하고 있습니다.",
        "status_low": "🟢 **52주 최저점 근접 구역 (바닥권 메리트):** 현재 주가는 52주 가격 밴드 하단에 있어 가격 부담이 적습니다.",
        "status_mid": "🟡 **중간 밴드 구역 (균형 가격):** 현재 주가는 52주 중간 이동평균선 부근에서 안정적인 흐름을 유지 중입니다.",
        "ichimoku_title": "일목 기술적 분석",
        "tenkan": "전환선 (단기 추세선)",
        "kijun": "기준선 (중기 균형선)",
        "signal": "일목 종합 판단 시그널",
        "detail_feedback": "🔍 실시간 차트 세부 진단 피드백",
        "chart_trend": "📈 핵심 지표 시각화 트렌드 (최근 60거래일 동향)",
        "no_news": "ℹ️ 현재 제공된 실시간 뉴스가 없습니다.",
        "latest_news": "최신 뉴스"
    },
    "en": {
        "title": "📊 Corporate Financial Analysis Tool",
        "subtitle": "Advanced Financial Diagnostics System - Comprehensive Technical & Fundamental Structural Mapping",
        "market_select": "Select Market:",
        "market_us": "🇺🇸 US Stocks (Yahoo)",
        "market_kr": "🇰🇷 KR Stocks (DART)",
        "search_method": "Select Search Method:",
        "by_name": "By Company Name",
        "enter_ticker": "Enter US Stock Ticker (e.g., AAPL):",
        "enter_ticker_kr": "Enter 6-digit KR Stock Code (e.g., 005380):",
        "enter_name": "Enter Company Name (e.g., Apple, Tesla, Oracle):",
        "select_company": "Select exact company:",
        "search_error": "⚠️ Search limit reached or network delay. Using 'By Ticker' method works without interruption.",
        "fetch_error": "⚠️ Failed to fetch data. Please check if the US ticker is correct or try again later.",
        "fetch_error_kr": "⚠️ Failed to fetch Korean stock data. Please check your DART API Key and Stock Code.",
        "insufficient_data": "📊 Insufficient financial data columns for comparative analysis.",
        "partial_data_info": "Currently showing price and technical indicators only. Additional financial metrics will appear automatically once DART API access is restored.",
        "tab_overview": "📌 Overview",
        "tab_ichimoku": "📐 Ichimoku Indicator",
        "tab_bs": "🏢 Balance Sheet",
        "tab_ratios": "📊 Ratios",
        "tab_valuation": "📉 Valuation",
        "tab_tech": "📊 Indicators (Tech)",
        "tab_tech_title": "📊 Technical Indicator Summary",
        "tech_insufficient_data": "Not enough data to compute technical indicators. Please check recent price and volume trends.",
        "rsi_overbought": "RSI is above 70, indicating potential overbought conditions and a possible pullback.",
        "rsi_oversold": "RSI is below 30, indicating potential oversold conditions and a possible rebound.",
        "rsi_neutral": "RSI is in a neutral zone. Confirm direction with additional indicators.",
        "macd_bullish": "MACD is above its signal line, suggesting bullish momentum.",
        "macd_bearish": "MACD is below its signal line, suggesting bearish pressure.",
        "macd_neutral": "MACD is close to its signal line, so the trend is not clearly defined.",
        "obv_up": "OBV is rising, indicating volume accumulation on up-days.",
        "obv_down": "OBV is falling, indicating volume pressure on down-days.",
        "obv_flat": "OBV is flat, suggesting weak volume conviction and a need for trend confirmation.",
        "tech_summary_title": "Current Technical Situation",
        "tech_summary_intro": "The following insights are based on the selected company’s recent price and volume behavior.",
        "tab_news": "📰 News",
        "report_title": "📝 Financial & Stock Comprehensive Diagnostic Report",
        "target_comp": "Target Company",
        "section1": "🔍 1. Recent Stock Price Level & Valuation Evaluation",
        "section2": "📊 2. Core Financial Status Scoring",
        "section3": "💡 3. Final Investment Strategy Guideline (CVP Fusion)",
        "curr_price": "Current Price",
        "range_52": "52-Week Price Range",
        "at_location": "Currently at",
        "location_end": "of the variation range",
        "avg_50": "Short-term Equilibrium Price (50-Day Avg)",
        "multiple_analysis": "Multiple Analysis: Current PER is",
        "ichimoku_analysis": "##### 📐 Ichimoku Cloud Trend Momentum Analysis",
        "growth_score": "Growth Score (Revenue Change)",
        "profit_score": "Profitability Score (Net Income Change)",
        "stability_score": "Debt Stability (Debt to Equity)",
        "liquidity_score": "Liquidity Risk (Current Ratio)",
        "total_score_text": "Comprehensive Financial Health Rating",
        "excellent": "✅ Excellent",
        "stagnant": "❌ Stagnant",
        "safe": "✅ Safe",
        "high_debt": "🚨 High Debt",
        "caution_cash": "🚨 Liquidity Caution",
        "report_good": "💎 **Financial Summary:** Fundamentals are exceptionally strong. A dollar-cost averaging strategy during stock corrections is recommended.",
        "report_neutral": "⚠️ **Financial Summary:** Slowdown observed in specific growth or stability metrics. Margins should be tracked closely.",
        "report_bad": "🚨 **Financial Summary:** Risks regarding negative growth and liquidity. A conservative investment approach is advised.",
        "guideline_1": "1. **Cost Structure Insight:** The estimated Break-Even Point (BEP) revenue for the current quarter is **{currency}{bep_sales:,.0f}**. Since current revenue safely exceeds BEP, the company is in a profitability expansion phase due to fixed-cost leverage.",
        "guideline_2": "2. **Working Capital Efficiency:** The Cash Conversion Cycle (CCC) is **{ccc:.1f} Days**, indicating smooth cash recovery. Check for inventory accumulation risks from supply chain issues.",
        "guideline_3": "3. **Final Conclusion:** Based on the value-per-share scaling estimates, the current price is reasonable relative to financial strength. However, consider short-term volatility and monitor global issues in the News tab.",
        "disclaimer": "⚠️ **Investment Disclaimer** * This analysis is for informational purposes based on financial statements and does not guarantee investment returns or constitute advice. All investment decisions are the sole responsibility of the user, and this system is not liable for any losses that may result from the use of this information.",
        "status_high": "🔴 **Near 52-Week High (Overheated Zone):** The stock price is currently at the top of its 52-week band.",
        "status_low": "🟢 **Near 52-Week Low (Bargain Zone):** The price is at the bottom of the band, presenting lower downside risk.",
        "status_mid": "🟡 **Mid-Band Zone (Equilibrium Price):** The price is stable near its 50-day moving average.",
        "ichimoku_title": "Ichimoku Technical Analysis",
        "tenkan": "Tenkan-Sen (Short-term)",
        "kijun": "Kijun-Sen (Medium-term)",
        "signal": "Ichimoku Signal Status",
        "detail_feedback": "🔍 Real-time Chart Detailed Diagnostic Feedback",
        "chart_trend": "📈 Key Metrics Visualization Trend (Last 60 Trading Days)",
        "no_news": "ℹ️ No real-time news articles available currently.",
        "latest_news": "Latest News"
    },
    "es": {
        "title": "📊 Herramienta de Análisis Financiero Corporativo",
        "subtitle": "Sistema Avanzado de Diagnóstico Financiero - Mapeo Técnico y Fundamental",
        "market_select": "Seleccionar Mercado:",
        "market_us": "🇺🇸 Acciones EE. UU. (Yahoo)",
        "market_kr": "🇰🇷 Acciones KR (DART)",
        "search_method": "Seleccionar método de búsqueda:",
        "by_ticker": "Por Ticker/Código",
        "by_name": "Por nombre de la empresa",
        "enter_ticker": "Ingresar ticker US (ej: AAPL):",
        "enter_name": "Ingresar nombre de la empresa (ej: Samsung):",
        "enter_name_kr": "Ingresar nombre de la empresa (KR):",
        "select_company": "Seleccionar empresa exacta:",
        "search_error": "⚠️ Límite de búsqueda alcanzado o retraso de red. Use 'Por Ticker' para evitar interrupciones.",
        "fetch_error": "⚠️ Error al obtener datos. Verifique el ticker o inténtelo más tarde.",
        "fetch_error_kr": "⚠️ Error al obtener datos coreanos. Verifique su clave DART y el código.",
        "partial_data_warning": "⚠️ Faltan algunos datos financieros; el análisis será limitado.",
        "partial_data_info": "Actualmente solo se muestran precio e indicadores técnicos. Más métricas aparecerán cuando se restaure DART.",
        "tab_report": "📝 Informe",
        "tab_ichimoku": "📐 Ichimoku",
        "tab_ratios": "📊 Ratios",
        "tab_valuation": "📉 Valoración",
        "tab_tech": "📊 Indicadores (Técnicos)",
        "tab_tech_title": "📊 Resumen de Indicadores Técnicos",
        "tech_insufficient_data": "No hay datos suficientes para calcular indicadores técnicos. Revise precios y volumen.",
        "rsi_overbought": "RSI > 70: posible sobrecompra; atención a correcciones a corto plazo.",
        "rsi_oversold": "RSI < 30: posible sobreventa; potencial rebote.",
        "rsi_neutral": "RSI en zona neutral; confirme con otros indicadores.",
        "macd_bullish": "MACD por encima de la señal: impulso alcista.",
        "macd_bearish": "MACD por debajo de la señal: presión bajista.",
        "macd_neutral": "MACD cerca de la señal: tendencia no definida.",
        "obv_up": "OBV creciente: acumulación de volumen comprador.",
        "obv_down": "OBV decreciente: predominio del volumen vendedor.",
        "obv_flat": "OBV plano: convicción de volumen débil.",
        "tech_summary_title": "Situación técnica actual",
        "tech_summary_intro": "Las siguientes observaciones se basan en el comportamiento reciente de precio y volumen de la empresa seleccionada.",
        "tab_news": "📰 Noticias",
        "report_title": "📝 Informe Financiero y de Mercado",
        "target_comp": "Empresa objetivo",
        "section1": "🔍 1. Nivel de precio reciente y evaluación de valoración",
        "section2": "📊 2. Puntuación financiera clave",
        "section3": "💡 3. Directrices finales de inversión",
        "curr_price": "Precio actual",
        "range_52": "Rango 52 semanas",
        "at_location": "Actualmente en",
        "location_end": "del rango",
        "avg_50": "Promedio 50 días",
        "multiple_analysis": "Análisis de múltiplos: PER",
        "ichimoku_analysis": "##### 📐 Análisis Ichimoku",
        "growth_score": "Puntuación de crecimiento",
        "profit_score": "Puntuación de rentabilidad",
        "stability_score": "Estabilidad de deuda",
        "liquidity_score": "Riesgo de liquidez",
        "total_score_text": "Calificación financiera total",
        "excellent": "✅ Excelente",
        "stagnant": "❌ Estancado",
        "safe": "✅ Seguro",
        "high_debt": "🚨 Deuda alta",
        "caution_cash": "🚨 Precaución de liquidez",
        "report_good": "💎 Fundamentos sólidos. Considere compras escalonadas en correcciones.",
        "report_neutral": "⚠️ Desaceleración observada; siga los márgenes.",
        "report_bad": "🚨 Riesgos de crecimiento y liquidez; enfoque conservador.",
        "guideline_1": "1. BEP estimado: **{currency}{bep_sales:,.0f}**.",
        "guideline_2": "2. CCC: **{ccc:.1f} días**.",
        "guideline_3": "3. Conclusión: precio razonable vs fundamentos; supervise noticias.",
        "disclaimer": "⚠️ Este análisis es solo informativo y no constituye asesoramiento.",
        "status_high": "🔴 Cerca del máximo de 52 semanas.",
        "status_low": "🟢 Cerca del mínimo de 52 semanas.",
        "status_mid": "🟡 Zona media (precio de equilibrio).",
        "ichimoku_title": "Análisis Ichimoku",
        "tenkan": "Tenkan-Sen",
        "kijun": "Kijun-Sen",
        "signal": "Señal Ichimoku",
        "detail_feedback": "🔍 Retroalimentación detallada",
        "chart_trend": "📈 Tendencia (Últimos 60 días)",
        "no_news": "ℹ️ No hay noticias disponibles.",
        "latest_news": "Últimas noticias"
    }
}
