MESSAGES = {
    "ko": {
        "title": "📊 기업 재무 분석 도구",
        "subtitle": "고급 재무 진단 시스템 - 포괄적인 기술적 및 기본적 구조 매핑",
        "market_select": "시장 선택:",
        "market_us": "🇺🇸 미국 주식 (Yahoo Finance)",
        "market_kr": "🇰🇷 한국 주식 (FDR + DART)",
        "search_method": "검색 방법 선택:",
        "by_ticker": "티커/종목코드로 검색",
        "by_name": "회사명으로 검색",
        "enter_ticker": "미국 주식 티커 입력 (예: AAPL):",
        "enter_ticker_kr": "한국 주식 종목코드 6자리 입력 (예: 005380):",
        "enter_name": "회사명 입력 (예: Apple, Tesla, Oracle):",
        "enter_name_kr": "회사명 입력 (예: 현대차, 삼성전자, 카카오):",
        "select_company": "정확한 회사 선택:",
        "search_error": "⚠️ 검색 한계량 도달 혹은 네트워크 지연이 발생했습니다. 티커 검색 방식을 이용하시면 막힘없이 사용 가능합니다.",
        "search_error_kr": "⚠️ 한국 주식 종목 검색 중 오류가 발생했습니다. 종목 코드(6자리 숫자)로 직접 입력해 주세요.",
        "fetch_error": "⚠️ 종목의 데이터를 가져오지 못했습니다. 올바른 US 티커 명칭인지 확인하시거나 잠시 후 다시 검색해 주세요.",
        "fetch_error_kr": "⚠️ 한국 주식 데이터를 가져오지 못했습니다. DART API Key가 올바른지, 종목 코드가 맞는지 확인해 주세요.",
        "insufficient_data": "📊 재무 데이터의 열 개수가 비교 분석하기에 충분하지 않습니다.",
        "tab_report": "📝 종합의견 (Report)",
        "tab_overview": "📌 개요 (Overview)",
        "tab_ichimoku": "📐 일목균형표 (Ichimoku)",
        "tab_bs": "🏢 재무상태표 (Balance Sheet)",
        "tab_ratios": "📊 주요 비율 (Ratios)",
        "tab_valuation": "📉 가치평가 (Valuation)",
        "tab_news": "📰 뉴스 (News)",
        "report_title": "📝 실시간 재무·주가 종합 진단 보고서",
        "target_comp": "대상 기업",
        "section1": "🔍 1. 최근 주가 수준 및 기술적·밸류에이션 평가",
        "section2": "📊 2. 핵심 재무 상태 스코어링",
        "section3": "💡 3. 최종 투자 전략 가이드라인 (CVP 융합)",
        "curr_price": "현재 주가",
        "range_52": "52주 주가 변동 범위",
        "at_location": "현재 변동폭의",
        "location_end": "지점 위치",
        "avg_50": "단기 균형 가격 (50일 평균)",
        "multiple_analysis": "멀티플 분석: 현재 PER 지표는",
        "ichimoku_analysis": "##### 📐 일목균형표(Ichimoku) 추세 모멘텀 분석",
        "growth_score": "성장성 점수 (매출액 변동)",
        "profit_score": "수익성 점수 (당기순이익 변동)",
        "stability_score": "부채 안정성 (부채비율)",
        "liquidity_score": "유동성 리스크 (유동비율)",
        "total_score_text": "종합 재무 건전성 평점",
        "excellent": "✅ 우수",
        "stagnant": "❌ 정체",
        "safe": "✅ 안전",
        "high_debt": "🚨 부채 과다",
        "caution_cash": "🚨 현금 주의",
        "report_good": "💎 **재무 종합 의견:** 펀더멘탈이 대단히 우량한 기업입니다. 주가 조정 발생 시 분할 매수 접근 전략이 유효합니다.",
        "report_neutral": "⚠️ **재무 종합 의견:** 성장성 혹은 안정성 중 특정 지표의 둔화가 관찰됩니다. 마진율 변동 추이를 추적 관찰해야 합니다.",
        "report_bad": "🚨 **재무 종합 의견:** 전반적인 재무 지표 역성장 및 유동성 리스크가 우려됩니다. 보수적인 투자 관점이 필요합니다.",
        "guideline_1": "1. **비용 구조 개방:** 본 기업의 현재 분기 추정 손익분기점(BEP) 매출액은 **{currency}{bep_sales:,.0f}**입니다. 현재 매출이 손익분기점을 안전하게 상회하고 있으므로 고정비 레버리지 효과에 따른 수익성 확대 국면입니다.",
        "guideline_2": "2. **운전 자본 효율성:** 현금전환주기(CCC)가 **{ccc:.1f}일**로 측정되어 자금 회수 속도가 원활한 편입니다. 공급망 리스크에 따른 재고자산 누적 여부를 체크하시기 바랍니다.",
        "guideline_3": "3. **최종 결론:** 본 재무분석 시스템의 추정치인 주당 가치 스케일링을 기준으로 볼 때, 현재 주가는 재무 기초체력 대비 합리적인 흐름을 보이고 있으나, 단기 변동성을 감안하여 실시간 뉴스 탭에 올라오는 글로벌 이슈들을 병행 모니터링하시기 바랍니다.",
        "disclaimer": "⚠️ **Investment Disclaimer** ※ 본 자료 및 검토의견은 재무제표와 관련 자료를 기초로 작성된 참고용 정보이며, 투자 권유 또는 투자 수익을 보장하는 내용이 아닙니다. 투자 결정에 대한 최종 책임은 사용자에게 있으며, 이 정보로 인한 손해에 대해 본 시스템은 책임을 지지 않습니다.",
        "status_high": "🔴 **52주 최고점 근접 구역 (과열 경계):** 현재 주가는 52주 가격 밴드 최상단에 위치하고 있습니다.",
        "status_low": "🟢 **52주 최저점 근접 구역 (바닥권 메리트):** 현재 주가는 52주 가격 밴드 하단에 있어 가격 부담이 적습니다.",
        "status_mid": "🟡 **중간 밴드 구역 (균형 가격):** 현재 주가는 52주 중간 이동평균선 부근에서 안정적인 흐름을 유지 중입니다.",
        "ichimoku_title": "일목 기술적 분석",
        "tenkan": "전환선 (단기 추세선)",
        "kijun": "기준선 (중기 균형선)",
        "signal": "일목 종합 판단 시그널",
        "detail_feedback": "🔍 실시간 차트 세부 진단 피드백",
        "chart_trend": "📈 핵심 지표 시각화 트렌드 (최근 60거래일 동향)",
        "no_news": "ℹ️ 현재 제공된 실시간 뉴스가 없습니다.",
        "latest_news": "최신 뉴스"
    },
    "en": {
        "title": "📊 Corporate Financial Analysis Tool",
        "subtitle": "Advanced Financial Diagnostics System - Comprehensive Technical & Fundamental Structural Mapping",
        "market_select": "Select Market:",
        "market_us": "🇺🇸 US Stocks (Yahoo)",
        "market_kr": "🇰🇷 KR Stocks (DART)",
        "search_method": "Select Search Method:",
        "by_ticker": "By Ticker/Code",
        "by_name": "By Company Name",
        "enter_ticker": "Enter US Stock Ticker (e.g., AAPL):",
        "enter_ticker_kr": "Enter 6-digit KR Stock Code (e.g., 005380):",
        "enter_name": "Enter Company Name (e.g., Apple, Tesla, Oracle):",
        "enter_name_kr": "Enter Company Name (e.g., Hyundai, Samsung, Kakao):",
        "select_company": "Select exact company:",
        "search_error": "⚠️ Search limit reached or network delay. Using 'By Ticker' method works without interruption.",
        "search_error_kr": "⚠️ Error searching Korean stocks. Please enter the 6-digit stock code directly.",
        "fetch_error": "⚠️ Failed to fetch data. Please check if the US ticker is correct or try again later.",
        "fetch_error_kr": "⚠️ Failed to fetch Korean stock data. Please check your DART API Key and Stock Code.",
        "insufficient_data": "📊 Insufficient financial data columns for comparative analysis.",
        "tab_report": "📝 Report",
        "tab_overview": "📌 Overview",
        "tab_ichimoku": "📐 Ichimoku Indicator",
        "tab_bs": "🏢 Balance Sheet",
        "tab_ratios": "📊 Ratios",
        "tab_valuation": "📉 Valuation",
        "tab_news": "📰 News",
        "report_title": "📝 Financial & Stock Comprehensive Diagnostic Report",
        "target_comp": "Target Company",
        "section1": "🔍 1. Recent Stock Price Level & Valuation Evaluation",
        "section2": "📊 2. Core Financial Status Scoring",
        "section3": "💡 3. Final Investment Strategy Guideline (CVP Fusion)",
        "curr_price": "Current Price",
        "range_52": "52-Week Price Range",
        "at_location": "Currently at",
        "location_end": "of the variation range",
        "avg_50": "Short-term Equilibrium Price (50-Day Avg)",
        "multiple_analysis": "Multiple Analysis: Current PER is",
        "ichimoku_analysis": "##### 📐 Ichimoku Cloud Trend Momentum Analysis",
        "growth_score": "Growth Score (Revenue Change)",
        "profit_score": "Profitability Score (Net Income Change)",
        "stability_score": "Debt Stability (Debt to Equity)",
        "liquidity_score": "Liquidity Risk (Current Ratio)",
        "total_score_text": "Comprehensive Financial Health Rating",
        "excellent": "✅ Excellent",
        "stagnant": "❌ Stagnant",
        "safe": "✅ Safe",
        "high_debt": "🚨 High Debt",
        "caution_cash": "🚨 Liquidity Caution",
        "report_good": "💎 **Financial Summary:** Fundamentals are exceptionally strong. A dollar-cost averaging strategy during stock corrections is recommended.",
        "report_neutral": "⚠️ **Financial Summary:** Slowdown observed in specific growth or stability metrics. Margins should be tracked closely.",
        "report_bad": "🚨 **Financial Summary:** Risks regarding negative growth and liquidity. A conservative investment approach is advised.",
        "guideline_1": "1. **Cost Structure Insight:** The estimated Break-Even Point (BEP) revenue for the current quarter is **{currency}{bep_sales:,.0f}**. Since current revenue safely exceeds BEP, the company is in a profitability expansion phase due to fixed-cost leverage.",
        "guideline_2": "2. **Working Capital Efficiency:** The Cash Conversion Cycle (CCC) is **{ccc:.1f} Days**, indicating smooth cash recovery. Check for inventory accumulation risks from supply chain issues.",
        "guideline_3": "3. **Final Conclusion:** Based on the value-per-share scaling estimates, the current price is reasonable relative to financial strength. However, consider short-term volatility and monitor global issues in the News tab.",
        "disclaimer": "⚠️ **Investment Disclaimer** * This analysis is for informational purposes based on financial statements and does not guarantee investment returns or constitute advice. All investment decisions are the sole responsibility of the user, and this system is not liable for any losses that may result from the use of this information.",
        "status_high": "🔴 **Near 52-Week High (Overheated Zone):** The stock price is currently at the top of its 52-week band.",
        "status_low": "🟢 **Near 52-Week Low (Bargain Zone):** The price is at the bottom of the band, presenting lower downside risk.",
        "status_mid": "🟡 **Mid-Band Zone (Equilibrium Price):** The price is stable near its 50-day moving average.",
        "ichimoku_title": "Ichimoku Technical Analysis",
        "tenkan": "Tenkan-Sen (Short-term)",
        "kijun": "Kijun-Sen (Medium-term)",
        "signal": "Ichimoku Signal Status",
        "detail_feedback": "🔍 Real-time Chart Detailed Diagnostic Feedback",
        "chart_trend": "📈 Key Metrics Visualization Trend (Last 60 Trading Days)",
        "no_news": "ℹ️ No real-time news articles available currently.",
        "latest_news": "Latest News"
    }
}
